AWSTemplateFormatVersion: '2010-09-09'
Description: This is for Creating a new EC2 instance

#Parameters:
#  ElasticIpAllocationId:
#    Type: String
#    Description: ID of the existing Elastic IP to attach to the EC2 instance
    
#  ExistingVolumeId:
#    Type: String
#    Description: ID of the existing EBS volume to attach to the EC2 instance    

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-022e1a32d3f742bd8
      SecurityGroupIds:
        - !Ref ITBD
      KeyName: Splunk_test.pem

  ITBD:
    Type: AWS::EC2::SecurityGroup
    Properties:
         GroupId: launch-wizard-20

  #MyElasticIp:
  #  Type: AWS::EC2::EIP
  #  Properties:
  #    InstanceId: !Ref MyEC2Instance
  #    AllocationId: !Ref ElasticIpAllocationId
  
  #MyVolumeAttachment:
  #  Type: AWS::EC2::VolumeAttachment
  #  Properties:
  #    InstanceId: !Ref MyEC2Instance
  #    VolumeId: !Ref ExistingVolumeId
  #    Device: /dev/sdf # The device name to which the volume will be attached (change it according to your requirement)

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: ITBD-Production  
      MinSize: 1
      MaxSize: 4  
      DesiredCapacity: 1  
      AvailabilityZones: us-east-1 # Deploy the instance in the same region as the template

Outputs:
  InstanceId:
    Description: The ID of the newly created EC2 instance
    Value: !Ref MyEC2Instance
